### ISSUE TITLE
Instead of own implementation, just re-export frame types provided by libc? 

### ISSUE THREAD

**Issue by jreppnow** [socketcan-rs/socketcan-rs#30]
(Making an extra ticket explicitly not to disrupt the PR #16 even further..)

As @fpagliughi has stated in the comments for PR #16, the ```libc``` crate already has correct definitions for both the frame structs (2.0 and FD) -> this crate could consequentually just ```pub use``` them (possibly assigning a backwards compatible name) and implement its added logic as traits on top.

Once the current sleugh of PRs is done with an if the maintainers agree, I would see if that can be done easily.

**Comment by fpagliughi** [comment]
Nearly all the low-level types are now defined in the `libc` crate, like `sockaddr_can`, `can_filter`, etc, with some safe, wrappers in `nix`, though the nix coverage is less complete in nix (like no `CanAddr`).
But it would be great to get this suport pushed upstream.

We could use the low-level definitions, but probably want to wrap them in our own types to both provide Rust standard naming (like `CanAddr` rather than `can_addr`),  and also to make them into our own types so that we can implement traits on them etc. We can also make them workable with the libc types, like:

```
struct CanAddr(libc::sockaddr_can);

impl AsRef<libc::sockaddr_can> for CanAddr {
    fn as_ref(&self) -> &libc::sockaddr_can {
        &self.0
    }
}
```
